import enum
import uuid
from datetime import datetime

from sqlalchemy import (
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Numeric,
    String,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class RideStatus(str, enum.Enum):
    REQUESTED = "requested"
    MATCHED = "matched"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class RideNotFoundError(Exception):
    """Raised when an operation is attempted against a ride id that doesn't
    exist. Lives here (not in ride_service.py/matcher.py individually) since
    both already depend on this module for RideStatus/Ride."""


class InvalidRideStateError(Exception):
    """Raised when a ride's status doesn't allow the requested transition --
    either because it was never valid (e.g. completing a REQUESTED ride) or
    because a concurrent operation changed it first (e.g. match_ride losing
    a race to a concurrent cancel_ride). Shared by match_ride, cancel_ride,
    and complete_ride: all three now go through RideRepository.
    transition_status's atomic conditional UPDATE, and this is the single
    signal for "that conditional UPDATE affected zero rows." See
    INTERVIEW_PREP.md's Slice 6 section for the concurrency design this is
    part of."""


class Ride(Base):
    __tablename__ = "rides"

    # Slice 3's durable correctness boundary: at most one row here may have a
    # given driver_id while status is active. Declared here (not just in the
    # Alembic migration) so tests/conftest.py's Base.metadata.create_all(),
    # which builds the test schema straight from these models rather than
    # running migrations, actually gets this constraint too -- otherwise the
    # test database and real deployments would silently disagree about what's
    # enforced. Must stay in sync with the partial index created by migration
    # 4400761b43ec.
    # Slice 4's idempotency guarantee: a given idempotency_key can back at
    # most one ride, ever. Explicitly named (not autogenerated) to match this
    # project's pattern of intentional constraint names. NULL-safe by default
    # -- Postgres unique constraints treat multiple NULLs as non-conflicting,
    # so rides created without a key never collide with each other; no
    # postgresql_where scoping is needed the way the constraint below needs
    # one.
    __table_args__ = (
        Index(
            "ux_rides_one_active_ride_per_driver",
            "driver_id",
            unique=True,
            postgresql_where=text(
                "driver_id IS NOT NULL AND status IN ('requested', 'matched', 'in_progress')"
            ),
        ),
        UniqueConstraint("idempotency_key", name="uq_rides_idempotency_key"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    rider_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("riders.id"), nullable=False, index=True
    )
    # Nullable: a ride exists in "requested" status before any driver is matched.
    driver_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("drivers.id"), nullable=True, index=True
    )

    status: Mapped[RideStatus] = mapped_column(
        Enum(
            RideStatus,
            name="ride_status",
            native_enum=True,
            values_callable=lambda enum_cls: [member.value for member in enum_cls],
        ),
        nullable=False,
        default=RideStatus.REQUESTED,
        server_default=RideStatus.REQUESTED.value,
        index=True,
    )

    pickup_lat: Mapped[float] = mapped_column(Float, nullable=False)
    pickup_lng: Mapped[float] = mapped_column(Float, nullable=False)

    matched_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Money and multipliers use Numeric, not Float, to avoid binary floating-point
    # rounding errors in fares. Both are unset until the matching/pricing slices
    # (2 and 5) compute them.
    fare: Mapped[float | None] = mapped_column(Numeric(10, 2), nullable=True)
    surge_multiplier: Mapped[float | None] = mapped_column(Numeric(4, 2), nullable=True)

    # H3 zone the pickup falls into, used by Slice 5's surge aggregation.
    zone_id: Mapped[str | None] = mapped_column(String(20), nullable=True, index=True)

    # Client-supplied retry-deduplication key (Slice 4). Optional -- a ride
    # created without one is never deduplicated. Uniqueness enforced via
    # uq_rides_idempotency_key above, which is the actual guarantee; see
    # app/services/ride_service.py for how a race on this key is handled.
    idempotency_key: Mapped[str | None] = mapped_column(String(255), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
